### ISSUE TITLE
Newline in reaction.smirks crashes sdfTransformer.csh

### ISSUE THREAD

**Issue by jw-feng** [chemalot/chemalot#4]
Blank lines anywhere in a smirks file causes sdfTransformer.csh to crash

Exception in thread "main" java.lang.IllegalArgumentException:
	at autocorrelator.apps.MyUniMolecularTransform.<init>(SdfTransformer.java:751)
	at autocorrelator.apps.MyTransFormFactory.create(SdfTransformer.java:647)
	at autocorrelator.apps.SdfTransformer.readTransform(SdfTransformer.java:241)
	at autocorrelator.apps.SdfTransformer.addTransform(SdfTransformer.java:205)
	at autocorrelator.apps.SdfTransformer.getTransformations(SdfTransformer.java:196)
	at autocorrelator.apps.SdfTransformer.main(SdfTransformer.java:90)

**Comment by jw-feng** [comment]
Moving issue to autocorrelator package
